LATEX=pdflatex
BUILD1=$(LATEX) common_drain_amplifier_conc_wrap.tex
BUILD2=$(LATEX) common_source_amplifier_conc_wrap.tex

build: common_drain_amplifier_conc.tex common_drain_amplifier_conc_wrap.tex common_source_amplifier_conc.tex common_source_amplifier_conc_wrap.tex
	$(BUILD1)
	$(BUILD1)
	$(BUILD2)
	$(BUILD2)
